### ISSUE TITLE
--considerMultiAllelic flag to toggle handling of duplicate pos rows in (e.g.) 1KG VCFs

### ISSUE THREAD

**Issue by josephvitti** [broadinstitute/cms#11]
Currently, when scans.py encounters two rows with the same position, it merges them together by default (i.e., assuming consistent ancestral coding, it collapses all derived alleles together as 1 via a bitwise procedure). 

We want this procedure to take place iff the user specifies --considerMultiAllelic, and otherwise to skip these duplicate sites altogether (in 1KG P3 v5a dataset, ~9k such sites, about half of which are SNPs).

**Comment by tomkinsc** [comment]
Included in commit 2e389e2dd172700d090e8c00e3b9b8a246ba853f.
