### ISSUE TITLE
selscan's norm function for iHS expects 6 entries of input

### ISSUE THREAD

**Issue by josephvitti** [broadinstitute/cms#14]
selscan_ihs now gives left and right ancestral/derived iHH scores as part of output (which is awesome!) but selscan_norm_ihs does not anticipate this, and throws the following error:

ERROR: line 2 has 10 columns, but expected 6 columns.

(these scores themselves do not need to be normalized, selscan_norm_ihs just needs to ignore them)

**Comment by tomkinsc** [comment]
I can make this change to have `norm` ignore the four extra columns of left/right ancestral/derived that are included when the flag `--ihs-detail` is specified. Stay tuned for a commit on my branch of selscan and then a pull request on szpiech/selscan.

**Comment by tomkinsc** [comment]
Addressed in https://github.com/szpiech/selscan/pull/14
