### ISSUE TITLE
gratuitous selscan install

### ISSUE THREAD

**Issue by josephvitti** [broadinstitute/cms#150]
When I run selscan from scans.py in an active virtual environment, it will sometime try to install selscan anyway (which then crashes due to some weird recursion issue, it looks like). A clean venv fixes the problem, but then after calling scans.py once it comes back. Based on the debug message, perhaps something is going wrong [here](https://github.com/broadinstitute/cms/blob/master/cms/tools/__init__.py#L272)ish? 

`(cms-env3)hw-uger-1000:/idi/sabeti-scratch/jvitti 16:39:24 1009 $ python cms/cms/scans.py selscan_xpehh /idi/sabeti-scratch/jvitti/sims/nulldefault_constantsize/sel1/sel_sims/sel_0.50/rep383_1.tped /idi/sabeti-scratch/jvitti/scores/nulldefault_constantsize/sel1/xpehh/sel_0.50/rep_383_1_3 /idi/sabeti-scratch/jvitti/sims/nulldefault_constantsize/sel1/sel_sims/sel_0.50/rep383_3.tped --threads 7`

> 2016-10-19 16:41:15,374 - cmd:112:main_argparse - INFO - software version: 2.0.0-beta-4-g708555a, python version: 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
> 2016-10-19 16:41:15,375 - cmd:115:main_argparse - INFO - command: cms/cms/scans.py selscan_xpehh inputTped=/idi/sabeti-scratch/jvitti/sims/nulldefault_constantsize/sel1/sel_sims/sel_0.50/rep383_1.tped tmpDirKeep=False truncOk=False tmpDir=/tmp/3396933.1.interactive loglevel=DEBUG threads=7 outFile=/idi/sabeti-scratch/jvitti/scores/nulldefault_constantsize/sel1/xpehh/sel_0.50/rep_383_1_3 gapScale=20000 maf=0.05 inputRefTped=/idi/sabeti-scratch/jvitti/sims/nulldefault_constantsize/sel1/sel_sims/sel_0.50/rep383_3.tped
> 2016-10-19 16:41:15,375 - cmd:127:main_argparse - DEBUG - using tempDir: /tmp/3396933.1.interactive/tmp-scans-selscan_xpehh-a0c4koji
> 2016-10-19 16:41:15,375 - **init**:247:**init** - DEBUG - CONDA_ENV_PATH found
> 2016-10-19 16:41:20,804 - **init**:412:_attempt_install - DEBUG - Attempting install...
> 2016-10-19 16:41:20,804 - __init__:493:install_package - DEBUG - Creating conda environment and installing package selscan=1.1.0b
> 2016-10-19 16:41:33,764 - misc:240:run_and_print - INFO - {
>   "error": "An unexpected error has occurred, please consider sending the\nfollowing traceback to the conda GitHub issue tracker at:\n\n    https://github.com/conda/conda/issues\n\nInclude the output of the command 'conda info' in your report.\n\nTraceback (most recent call last):\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/cli/main.py\", line 146, in args_func\n    args.func(args, p)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/cli/main_create.py\", line 49, in execute\n    install.install(args, parser, 'create')\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/cli/install.py\", line 424, in install\n    plan.execute_actions(actions, index, verbose=not args.quiet)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/plan.py\", line 539, in execute_actions\n    inst.execute_instructions(plan, index, verbose)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/instructions.py\", line 149, in execute_instructions\n    cmd(state, arg)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/instructions.py\", line 92, in LINK_CMD\n    link(state['prefix'], arg, index=state['index'])\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/instructions.py\", line 88, in link\n    install.link(pkgs_dir, prefix, dist, lt, index=index)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/install.py\", line 624, in link\n    os.makedirs(dst_dir)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 231, in makedirs\n    makedirs(head, mode, exist_ok)\n  File \"/home/unix/vitti/miniconda3/lib/python3.5/os.py\", line 241, in makedirs\n    mkdir(name, mode)\nOSError: [Errno 36] File name too long: '/idi/sabeti-scratch/jvitti/total 120M\ndrwxrwxr-x  2 vitti  6.1K Oct 19 15:56 \x1b[0m\x1b[38;5;27m.\x1b[0m/\ndrwxrwxr-x 16 vitti   323 Oct 19 15:21 \x1b[38;5;27m..\x1b[0m/\n-rwxr-xr-x  2 vitti  5.8K Sep 18  2015 \x1b[38;5;34m.gcc-post-link.sh\x1b[0m_\n-rwxr-xr-x  2 vitti   427 Sep 18  2015 \x1b[38;5;34m.gcc-pre-unlink.sh\x1b[0m_\n-rwxrwxr-x  3 vitti  9.8K May 31 17:24 \x1b[38;5;34m.openssl-libcrypto-fix\x1b[0m_\n-rw-rw-r--  3 vitti   213 May 31 17:24 \x1b[44;38;5;15m.openssl-post-link.sh\x1b[0m\nlrwxrwxrwx  1 vitti     8 Oct 19 15:16 \x1b[38;5;51m2to3\x1b[0m -> \x1b[38;5;34m2to3-3.5\x1b[0m_\n-rwxrwxr-x  1 vitti   130 Oct 19 15:17 \x1b[38;5;34m2to3-3.5\x1b[0m_\n-rwxr-xr-x  1 vitti   68K Oct 19 15:17 \x1b[38;5;34mace2sam\x1b[0m_\nlrwxrwxrwx  1 vitti    40 Oct 19 15:56 \x1b[38;5;51mactivate\x1b[0m -> \x1b[38;5;34m'\n",
>   "error_type": "UnexpectedError"
> }
> 
> Traceback (most recent call last):
>   File "cms/cms/scans.py", line 580, in <module>
>     util.cmd.main_argparse(**commands**, **doc**)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/cmd.py", line 130, in main_argparse
>     ret = args.func_main(args)
>   File "cms/cms/scans.py", line 365, in main_selscan_xpehh
>     gap_scale       = args.gapScale
>   File "/idi/sabeti-scratch/jvitti/cms/cms/tools/selscan.py", line 530, in execute_xpehh
>     toolCmd = [self.install_and_get_path()]
>   File "/idi/sabeti-scratch/jvitti/cms/cms/tools/**init**.py", line 109, in install_and_get_path
>     raise NameError("unsuccessful in installing " + type(self).**name**)
> NameError: unsuccessful in installing SelscanTool

**Comment by josephvitti** [comment]
@tomkinsc have you had this issue? Possibly when all CMS dependencies are [bundled](https://github.com/bioconda/bioconda-recipes/pull/2632) as a conda package, this won't matter?

**Comment by tomkinsc** [comment]
What is the output of `conda info` when you have the conda environment active?

**Comment by josephvitti** [comment]
`(cms-env3)hw-uger-1000:/idi/sabeti-scratch/jvitti 17:14:48 1085 $ conda info`

```
Current conda install:

             platform : linux-64
        conda version : 4.0.10
  conda-build version : not installed
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /home/unix/vitti/miniconda3  (writable)
  default environment : /home/unix/vitti/miniconda3/envs/cms-env3
     envs directories : /home/unix/vitti/miniconda3/envs
        package cache : /home/unix/vitti/miniconda3/pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/linux-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
                        https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/unix/vitti/.condarc
    is foreign system : False

```

**Comment by josephvitti** [comment]
possibly separate (?): when I [test-run scans.py](https://github.com/bioconda/bioconda-recipes/blob/cms/recipes/cms/meta.yaml#L110) as part of the CMS conda recipe, it throws the following error:

> /+ scans.py -h
> fatal: Not a git repository (or any of the parent directories): .git
> Traceback (most recent call last):
>   File "/Users/vitti/miniconda3/conda-bld/cms_1476912759382/_t_env/bin/scans.py", line 15, in <module>
>     import tools.selscan
>   File "/Users/vitti/miniconda3/conda-bld/cms_1476912759382/_t_env/opt/cms-2.0.0b/cms/tools/__init__.py", line 12, in <module>
>     import util.file
>   File "/Users/vitti/miniconda3/conda-bld/cms_1476912759382/_t_env/opt/cms-2.0.0b/cms/util/file.py", line 10, in <module>
>     import util.cmd
>   File "/Users/vitti/miniconda3/conda-bld/cms_1476912759382/_t_env/opt/cms-2.0.0b/cms/util/cmd.py", line 10, in <module>
>     __version__ = util.version.get_version()
>   File "/Users/vitti/miniconda3/conda-bld/cms_1476912759382/_t_env/opt/cms-2.0.0b/cms/util/version.py", line 63, in get_version
>     raise ValueError("Cannot find the version number!")
> ValueError: Cannot find the version number!
> TESTS FAILED: cms-2.0.0b-py35_0

**Comment by tomkinsc** [comment]
I'll look into these errors and get back to you.

**Comment by tomkinsc** [comment]
I see you merged #151. Did it fix the selscan install issue you were seeing? If not, you might try updating conda (`conda update conda`).

**Comment by josephvitti** [comment]
Oh, awesome! The issue persisted, but everything works now with the conda update. I had been using the earlier version due to [this issue](https://github.com/conda/conda/issues/3001) on UGER, but I'll give 4.2.9 a shot. Thanks very much!

**Comment by tomkinsc** [comment]
Please let me know if conda 4.2.9 works without issue on UGER. I briefly tried to replicate the selscan install issue under 4.0.10 and couldn't seem to do so. If you do need to roll back, I'll have to take another look at it. My first guess is that it is related to the depth of the conda environment in the filesystem hierarchy. Earlier versions of conda (including 4.0.10) had issues if the path containing the conda env was too long (i.e. too deep in the filesystem hierarchy). The limit used to be about 80 characters, but it has been raised at least once as part of more recent releases of conda. The selscan installer should use the currently active conda environment by default, or otherwise it will try to create one within `cms/cms/tools/conda-tools`. With the preceding path, a tools-based path may have been too long.

**Comment by josephvitti** [comment]
4.2.9 appears to work smoothly on UGER! thanks again 🙌

**Comment by josephvitti** [comment]
Hmm, I may have spoke too soon -- I'm seeing a familiar error, albeit more infrequently:

> ```
> Traceback (most recent call last):
>   File "/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
>     return_value = func(*args, **kwargs)
>   File "/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 93, in _main
>     activate.main()
>   File "/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/cli/activate.py", line 148, in main
>     conda.install.symlink_conda(prefix, context.root_dir, shell)
>   File "/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/install.py", line 532, in symlink_conda
>     symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
>   File "/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/install.py", line 549, in symlink_conda_hlp
>     symlink_fn(root_file, prefix_file)
> FileExistsError: [Errno 17] File exists: '/home/unix/vitti/miniconda3/bin/conda' -> '/home/unix/vitti/miniconda3/envs/cms-env3/bin/conda'
> ```

**Comment by tomkinsc** [comment]
Ok, I took a look at the conda source. It looks like an NFS delay-related race condition, where one cluster job tries to create a symlink after a symlink from a second cluster job has appeared between the existence check and symlink creation in the first job. The function responsible was [more basic](https://github.com/conda/conda/blob/4.0.10/conda/install.py#L414) in conda v4.0.10  than the symlink function [in v4.2.9](https://github.com/conda/conda/blob/4.2.9/conda/install.py#L535) (it didn't try to remove the symlink if it already exists), but that's not the real issue here. The exception handler in the 4.2.9 version that that would ordinarily ignore such errors is susceptible to the same race condition. 🙄 (`os.path.lexists(prefix_file)` may not be True in the exception handler, so the exception gets raised and the activate/deactivate script dies)

Let's try patching the `install.py` file of conda v4.2.9, and see what happens. If we can fix the issue, one of us can open a PR to contribute the fix over in the https://github.com/conda/conda repository and close [issue 3001](https://github.com/conda/conda/issues/3001).

Based on your stack trace above, open up `/home/unix/vitti/miniconda3/lib/python3.5/site-packages/conda/install.py` and replace the `symlink_conda_hlp()` function starting on line 535 with the following:

``` python
def symlink_conda_hlp(prefix, root_dir, where, symlink_fn):
    scripts = ["conda", "activate", "deactivate"]
    prefix_where = join(prefix, where)
    if not isdir(prefix_where):
        os.makedirs(prefix_where)
    for f in scripts:
        root_file = join(root_dir, where, f)
        prefix_file = join(prefix_where, f)
        try:
            # try to kill stale links if they exist
            if os.path.lexists(prefix_file):
                rm_rf(prefix_file)
            # if they're in use, they won't be killed.  Skip making new symlink.
            if not os.path.lexists(prefix_file):
                symlink_fn(root_file, prefix_file)
        except (IOError, OSError) as e:
            if (e.errno == errno.EEXIST) or (os.path.lexists(prefix_file) and
                    (e.errno in (errno.EPERM, errno.EACCES, errno.EROFS))):
                log.debug("Cannot symlink {0} to {1}. Ignoring since link already exists."
                          .format(root_file, prefix_file))
            else:
                raise
```

With this change conda should chug along if it can't create the symlink during activation, and it should still work since _one_ of the cluster jobs will have created it. There's a chance there'll be a new race condition if something tries to use the link before NFS can propagate it, but hopefully that will be much less likely.

Alternatively, you might try commenting out these lines:

``` python
            if os.path.lexists(prefix_file):
                rm_rf(prefix_file)
```

**Comment by tomkinsc** [comment]
Looks like someone else [had the same idea](https://github.com/conda/conda/issues/2837#issuecomment-238481622) in mind to fix the symlink issue. A better fix might be the following since it would address the removal problem as well:

`conda/install.py`:

``` python
def symlink_conda_hlp(prefix, root_dir, where, symlink_fn):
    scripts = ["conda", "activate", "deactivate"]
    prefix_where = join(prefix, where)
    if not isdir(prefix_where):
        os.makedirs(prefix_where)
    for f in scripts:
        root_file = join(root_dir, where, f)
        prefix_file = join(prefix_where, f)
        try:
            # try to kill stale links if they exist
            if os.path.lexists(prefix_file):
                rm_rf(prefix_file)
            # if they're in use, they won't be killed.  Skip making new symlink.
            if not os.path.lexists(prefix_file):
                symlink_fn(root_file, prefix_file)
        except (IOError, OSError) as e:
            if (os.path.lexists(prefix_file) and
                    (e.errno in (errno.EPERM, errno.EACCES, errno.EROFS, errno.EEXIST))):
                log.debug("Cannot symlink {0} to {1}. Ignoring since link already exists."
                          .format(root_file, prefix_file))
            elif (e.errno == errno.ENOENT):
                log.debug("Problem with symlink management {0} {1}. File may have been removed by another concurrent process." .format(root_file, prefix_file))
            elif (e.errno == errno.EEXIST)):
                log.debug("Problem with symlink management {0} {1}. File may have been created by another concurrent process." .format(root_file, prefix_file))
            else:
                raise
```
