### ISSUE TITLE
scans.py calls old version of selscan that rejects ten-column output for normalization

### ISSUE THREAD

**Issue by josephvitti** [broadinstitute/cms#16]
Output made from selscan with the --ihs-detail flag has ten columns. The old selscan normalization function throws an error at this, expecting six (normal, undetailed output). According to the selscan page (https://github.com/szpiech/selscan), norm v1.0.5 can handle this, but this version does not appear to be integrated into scans.py.

**Comment by tomkinsc** [comment]
Resolved offline.
