### ISSUE TITLE
scans.py error

### ISSUE THREAD

**Issue by taylorreiter** [broadinstitute/cms#200]
Hello,

I am running macOS 10.12.3 with python 2.7. I downloaded cms via instructions listed on http://broad-cms.readthedocs.io/en/latest/install.html. Installation did not prompt any errors, and I was able to establish my environment.

when running scans.py selscan_file_conversion:

`(cms-env2) MacBook:cms taylorreiter$ python scans.py selscan_file_conversion -h`

I receive the following error:
`Traceback (most recent call last):
  File "scans.py", line 15, in <module>
    import tools.selscan
  File "/Users/taylorreiter/Desktop/1000 genomes correlates/vcf_files/cms/cms/tools/__init__.py", line 15, in <module>
    import util.file
  File "/Users/taylorreiter/Desktop/1000 genomes correlates/vcf_files/cms/cms/util/file.py", line 10, in <module>
    import util.cmd
  File "/Users/taylorreiter/Desktop/1000 genomes correlates/vcf_files/cms/cms/util/cmd.py", line 10, in <module>
    __version__ = util.version.get_version()
  File "/Users/taylorreiter/Desktop/1000 genomes correlates/vcf_files/cms/cms/util/version.py", line 117, in get_version
    write_release_version(from_git)
  File "/Users/taylorreiter/Desktop/1000 genomes correlates/vcf_files/cms/cms/util/version.py", line 60, in write_release_version
    with open(release_file(), 'wt') as outf:
IOError: [Errno 13] Permission denied: '/Users/taylorreiter/Desktop/1000 genomes correlates/vcf_files/cms/cms/VERSION'`

`$ ls -lh`
returns
`total 320
-rw-r--r--   1 root  staff   141B Feb  3 10:53 FileConverter.py
-rwxr-xr-x   1 root  staff   257B Feb  3 10:53 cms_exceptions.py
-rw-r--r--   1 root  staff    20K Feb  3 10:53 cms_modeller.py
drwxr-xr-x  15 root  staff   510B Feb  3 10:53 combine
-rw-r--r--   1 root  staff    16K Feb  3 10:53 composite.py
drwxr-xr-x   6 root  staff   204B Feb  3 10:53 dists
-rw-r--r--   1 root  staff    22K Feb  3 10:53 likes_from_model.py
-rwxr-xr-x   1 root  staff   171B Feb  3 10:53 main.py
drwxr-xr-x  16 root  staff   544B Feb  3 10:53 model
drwxr-xr-x   6 root  staff   204B Feb  3 10:53 power
-rw-r--r--   1 root  staff    51K Feb  3 10:53 power.py
-rw-r--r--   1 root  staff   712B Feb  3 10:53 run_traj.py
-rwxr-xr-x   1 root  staff    26K Feb  3 10:53 scans.py
-rwxr-xr-x   1 root  staff   101B Feb  3 10:53 selection.py
drwxr-xr-x   5 root  staff   170B Feb  3 10:53 test
drwxr-xr-x   4 root  staff   136B Feb  3 10:53 tools
drwxr-xr-x  15 root  staff   510B Feb  3 10:53 util`

I'm not sure where to begin to resolve this issue. Any help would be greatly appreciated.

**Comment by josephvitti** [comment]
Hi Taylor, so it looks like it's getting hung up when python tries to import modules at the beginning of the scans.py script you're running. I think if you `rm` and then `touch` the `__init__.py` file, or use chmod to give yourself execute permission (I think `chmod u+X` off the top of my head but I'm not sure) it may solve the problem. Could you give either of those a try and let me know? This may be something I can build into the install process.

**Comment by taylorreiter** [comment]
Hi Joseph,

I used 
`$ chmod scans.py`
and received the same error message as above.

The directory I am in does not contain and _init_.py file, however every subdirectory does. I wasn't sure which to `rm` ...

**Comment by josephvitti** [comment]
Hi Taylor, sorry for being unclear -- I meant for you to do `chmod u+X` the `__init__.py` files. I think you may need to do this for each of them to allow python to correctly import from code within each directory. 

When you give the command `ls -la /Users/taylorreiter/Desktop/1000 genomes correlates/vcf_files/cms/cms/tools/__init__.py`, what is the output?

**Comment by tomkinsc** [comment]
It looks like the error is happening when CMS attempts to write its `VERSION` file (we don't hard-code the version in the source, so CMS tries to infer and store it for later). Can you try to create it manually to see if you have write permissions for the containing directory?

```echo "2.0.0-beta" > /Users/taylorreiter/Desktop/1000 genomes correlates/vcf_files/cms/cms/VERSION```

In the output of your `ls -lh` command, it also looks like the CMS files are owned by `root`, which they need not be. I'm guessing this is the result of the install process being run via `sudo` or by the root user. You may need to:
```chown -R $(whoami) "/Users/taylorreiter/Desktop/1000 genomes correlates/vcf_files/cms"``` 
(call with sudo as appropriate). 

It may also help to avoid spaces in the path:
 `[...]/1000 genomes correlates` 
could become: 
`[...]/1000_genomes_correlates`

**Comment by taylorreiter** [comment]
I took the spaces out of the directory name and ran `ls -la`:
`(cms-env2) MacBook:cms taylorreiter$ ls -la /Users/taylorreiter/Desktop/1000_genomes_correlates/vcf_files/cms/cms/tools/__init__.py`
`-rw-r--r--  1 root  staff  28776 Feb  3 10:53 /Users/taylorreiter/Desktop/1000_genomes_correlates/vcf_files/cms/cms/tools/__init__.py`

Checking permission, that may be my issue...
`(cms-env2) MacBook:cms taylorreiter$ echo "2.0.0-beta" > /Users/taylorreiter/Desktop/1000_genomes_correlates/vcf_files/cms/cms/VERSION`

`-bash: /Users/taylorreiter/Desktop/1000_genomes_correlates/vcf_files/cms/cms/VERSION: Permission denied`

I gave myself permission and the `scans.py selscan_file_conversion -h` output was as expected. 

Thank you so much for your help! I'll think to check permissions sooner in the future...
