### ISSUE TITLE
selscan_file_conversion throws unexpected error with X chromosome

### ISSUE THREAD

**Issue by josephvitti** [broadinstitute/cms#219]
This command on the Broad server `python /idi/sabeti-scratch/jvitti/cms/cms/scans.py selscan_file_conversion /idi/sabeti-scratch/jvitti/1kg_vcfs/regional/snps_1kg_chrX_BEB_148764000_158764000.recode.vcf.gz /idi/sabeti-scratch/ilya/gsvn/Data/Ilya_Data/genmaps/hm2/genetic_map_GRCh37_chrX.txt snps_1kg_chrX_BEB_148764000_158764000 /idi/sabeti-scratch/jvitti/1kg_tpeds/regional/ X` gives me the following error: 

> Traceback (most recent call last):
>   File "/idi/sabeti-scratch/jvitti/cms/cms/scans.py", line 580, in <module>
>     util.cmd.main_argparse(__commands__, __doc__)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/cmd.py", line 130, in main_argparse
>     ret = args.func_main(args)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/scans.py", line 136, in main_selscan_file_conversion
>     multi_alleli_merge_function               = args.multiAllelicMergeFunction)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/tools/selscan.py", line 174, in process_vcf_into_selscan_tped
>     of1l.write(lineToWrite1)
>   File "/home/unix/vitti/miniconda3/envs/cms-env3/lib/python3.5/gzip.py", line 258, in write
>     data = memoryview(data)
> TypeError: memoryview: a bytes-like object is required, not 'str'

Similar commands on autosomal files perform fine. The source file is bgzipped and Tabix-indexed.

**Comment by notestaff** [comment]
try adding --ploidy=1 after selscan_file_conversion for X chromosomes

**Comment by josephvitti** [comment]
I get the same error with `--ploidy=1`.

**Comment by notestaff** [comment]
the vcf file has both diploid and haploid samples (male & female), since , so one fix would be to split samples by ploidy and run the command twice.  i'll see if there is a simpler fix.

**Comment by notestaff** [comment]
simpler may be to split each diploid sample into two haploids and run with --ploidy=1, since for CMS purposes only the set of haploid genomes matters

**Comment by notestaff** [comment]
PR #220 should fix it; but i'm not sure how much handling of mixed-ploidy files has been tested in general, so maybe double-check the results.

**Comment by josephvitti** [comment]
cool, thanks @notestaff
