### ISSUE TITLE
Improvement on sample_header_line function (vcf reader)

### ISSUE THREAD

**Issue by gbss2** [broadinstitute/cms#222]
We had been struggling for a while with an error originated by the wrong assesment of the header by VCF reader. The error was originated by vcf_reader.py at line 83:

`                if line.find("CHROM", 1) > 0:
`

We solved the issue replacing CHROM by #CHROM

`                if line.find("#CHROM", 1) > 0:`

We suggest this modification because bcftools, while annotating VCF files, inserts a line like the one below and is not trivial to spot the cause of the error that pops up on selscan_file_conversion.

> (##bcftools_annotateCommand=annotate -a 1000G_Phase3_chr22.gz -h ancestral_allele.hdr -c CHROM,POS,AA 1000G_Phase3_chr22_noREF.vcf.gz)

Best Regards,

**Comment by tomkinsc** [comment]
Thank you; incorporated this in PR #224.
