### ISSUE TITLE
python-dateutil 2.3 missing from conda

### ISSUE THREAD

**Issue by mkzia** [broadinstitute/cms#227]
When I try to install the software via conda (v4.2.12) I get the following error message:

```
NoPackagesFoundError: Package missing in current linux-64 channels: 
  - python-dateutil 2.3*
```. 

Can I user a later version of dateutil?

**Comment by tomkinsc** [comment]
It should be fine to use a later version of `dateutil`. Please let us know if you encounter any issues as a result of doing so.

**Comment by mkzia** [comment]
I used version 2.4 and it worked fine.
