### ISSUE TITLE
permissions error for conda env create on Broad server

### ISSUE THREAD

**Issue by josephvitti** [broadinstitute/cms#49]
> **hw-uger-1080:/idi/sabeti-scratch/jvitti/test_github/cms 16:17:21 376 $ conda env create -f=conda-environment_py2.yaml -n cms-env**
> Using Anaconda Cloud api site https://api.anaconda.org
> Using Anaconda Cloud api site https://api.anaconda.org
> Using Anaconda Cloud api site https://api.anaconda.org
> Fetching package metadata ...........
> Solving package specifications: ..........
> Fetching packages ...
> ncurses-5.9-8. 100% |#################################################################################################################################################################| Time: 0:00:00   2.22 MB/s
> python-2.7.12- 100% |#################################################################################################################################################################| Time: 0:00:01  10.49 MB/s
> alabaster-0.7. 100% |#################################################################################################################################################################| Time: 0:00:00   4.05 MB/s
> boltons-16.4.1 100% |#################################################################################################################################################################| Time: 0:00:00   1.66 MB/s
> docutils-0.12- 100% |#################################################################################################################################################################| Time: 0:00:00   1.63 MB/s
> ecdsa-0.13-py2 100% |#################################################################################################################################################################| Time: 0:00:00 643.88 kB/s
> imagesize-0.7. 100% |#################################################################################################################################################################| Time: 0:00:00 606.38 kB/s
> markupsafe-0.2 100% |#################################################################################################################################################################| Time: 0:00:00   1.17 MB/s
> numpy-1.11.0-p 100% |#################################################################################################################################################################| Time: 0:00:01   4.95 MB/s
> peewee-2.8.0-p 100% |#################################################################################################################################################################| Time: 0:00:00   1.55 MB/s
> pycrypto-2.6.1 100% |#################################################################################################################################################################| Time: 0:00:00   1.77 MB/s
> pygments-2.1.3 100% |#################################################################################################################################################################| Time: 0:00:00   2.86 MB/s
> pytz-2016.4-py 100% |#################################################################################################################################################################| Time: 0:00:00   1.09 MB/s
> setuptools-23. 100% |#################################################################################################################################################################| Time: 0:00:00   1.51 MB/s
> six-1.10.0-py2 100% |#################################################################################################################################################################| Time: 0:00:00 595.35 kB/s
> snowballstemme 100% |#################################################################################################################################################################| Time: 0:00:00 687.56 kB/s
> sphinx_rtd_the 100% |#################################################################################################################################################################| Time: 0:00:00   2.08 MB/s
> wheel-0.29.0-p 100% |#################################################################################################################################################################| Time: 0:00:00 885.64 kB/s
> babel-2.3.3-py 100% |#################################################################################################################################################################| Time: 0:00:00   6.01 MB/s
> biopython-1.67 100% |#################################################################################################################################################################| Time: 0:00:00   4.32 MB/s
> jinja2-2.8-py2 100% |#################################################################################################################################################################| Time: 0:00:00   1.22 MB/s
> paramiko-1.16. 100% |#################################################################################################################################################################| Time: 0:00:00   1.28 MB/s
> pip-8.1.2-py27 100% |#################################################################################################################################################################| Time: 0:00:00   3.12 MB/s
> pysam-0.9.1-py 100% |#################################################################################################################################################################| Time: 0:00:01   4.02 MB/s
> python-dateuti 100% |#################################################################################################################################################################| Time: 0:00:00 994.95 kB/s
> scipy-0.17.0-n 100% |#################################################################################################################################################################| Time: 0:00:22   1.41 MB/s
> pandas-0.18.1- 100% |#################################################################################################################################################################| Time: 0:00:01  11.43 MB/s
> Extracting packages ...
> [      COMPLETE      ]|####################################################################################################################################################################################| 100%
> Linking packages ...
> An unexpected error has occurred, please consider sending the                                                                                                                                              |   4%
> following traceback to the conda GitHub issue tracker at:
> 
> ```
> https://github.com/conda/conda/issues
> ```
> 
> Include the output of the command 'conda info' in your report.
> 
> Traceback (most recent call last):
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/bin/conda-env", line 6, in <module>
>     sys.exit(conda_env.cli.main.main())
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
>     return args_func(args, parser)
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
>     exit_code = args.func(args, p)
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 99, in execute
>     installer.install(prefix, pkg_specs, args, env)
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/lib/python3.5/site-packages/conda_env/installers/conda.py", line 20, in install
>     plan.execute_actions(actions, index, verbose=not args.quiet)
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/lib/python3.5/site-packages/conda/plan.py", line 595, in execute_actions
>     inst.execute_instructions(plan, index, verbose)
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/lib/python3.5/site-packages/conda/instructions.py", line 136, in execute_instructions
>     cmd(state, arg)
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/lib/python3.5/site-packages/conda/instructions.py", line 79, in LINK_CMD
>     link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/lib/python3.5/site-packages/conda/install.py", line 1042, in link
>     with Locked(prefix), Locked(pkgs_dir):
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/lib/python3.5/site-packages/conda/lock.py", line 60, in **enter**
>     os.makedirs(self.lock_path)
>   File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/lib/python3.5/os.py", line 241, in makedirs
>     mkdir(name, mode)
> **PermissionError: [Errno 13] Permission denied: '/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda3_4.0.0/pkgs/.conda_lock-3985'**

**Comment by tomkinsc** [comment]
It may be best to rely on a [separate installation of Miniconda](http://conda.pydata.org/miniconda.html) rather than the Broad's dotkit.

That said, does it work if you set the `CONDA_ENVS_PATH` environment variable in your shell or `~/.my.bashrc` to a writable location?

`export CONDA_ENVS_PATH="$HOME/conda-envs-path"`
