### ISSUE TITLE
integrate option to normalize iHS/XP-EHH values using selscan 

### ISSUE THREAD

**Issue by josephvitti** [broadinstitute/cms#6]
Correlation between selscan/sweep iHS values matches that shown in Hernandez et al. 2014; we are ready to move forward with integrating selscan into the CMS 2.0 pipeline. We want to percolate up to the CMS 2.0 user some of selscan's normalization options (e.g. --bins, --crit-percent, --crit-val).

**Comment by tomkinsc** [comment]
OK, so this involves including norm in the build process for Selscan, and exposing a command line interface via cms/tools/selscan.py with the options inherent to norm.

**Comment by tomkinsc** [comment]
This has been addressed in dcd38644432a9d309e1cbd4d74f53a10cb8e9a10, is currently present in ct-cms, and will be merged from the ct-cms branch to master with the next pull request from that branch.
