### ISSUE TITLE
local installation issue

### ISSUE THREAD

**Issue by josephvitti** [broadinstitute/cms#7]
Issue with installation (pip -r install requirements.txt): Biopython fails because it can't find Numpy even though it's installed through Anacondas.

**Comment by tomkinsc** [comment]
This may just be an artifact of the pip install order. Are you able to "import Bio" while active inside the virtual environment?

**Comment by tomkinsc** [comment]
Resolved out of band with @josephvitti. Looks like biopython was indeed installed successfully.
