### ISSUE TITLE
scans.py calls incorrect binary to perform normalization with selscan

### ISSUE THREAD

**Issue by josephvitti** [broadinstitute/cms#87]
scans.py calls the "selscan" binary when it should call the "norm" binary. It looks like [this](https://github.com/broadinstitute/cms/blob/master/cms/tools/selscan.py#L579) is where that happens, but I'm unsure how to correct it -- @tomkinsc, can you please advise?

**Comment by josephvitti** [comment]
e.g., if I input
`python cms/cms/scans.py selscan_norm_ihs {files...}`
the following gets executed:
`/Users/vitti/miniconda3/envs/cms-env3/bin/selscan --ihs --files {...}`
whereas it should execute
`/Users/vitti/miniconda3/envs/cms-env3/bin/norm --ihs --files {...}`

**Comment by tomkinsc** [comment]
Could you please post the full command you ran so I can debug? Thanks!
